package com.rayssolartechnologies.tipcalc;

/*
 * Gayathri N Kannepalli
 * This activity class represents the event handling and state
 * of our first Tip Calculating app.
 */

import android.app.*;
import android.support.v7.app.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;
import java.lang.*;

public class MainActivity extends Activity implements View.OnClickListener {

    private Button button;
    private TextView tipAmount;
    private EditText billAmount, tipPercent;

    private void roll() {
        button = (Button)findViewById(R.id.button);
        billAmount = (EditText)findViewById(R.id.billAmount);
        tipPercent = (EditText)findViewById(R.id.tipPercent);
        tipAmount = (TextView)findViewById(R.id.tipAmount);

        button.setOnClickListener(this);

    }


    /*************************************************************************
     * BELOW THIS POINT IS CODE THAT WAS GENERATED BY ANDROID STUDIO THAT WE *
     * DID NOT MODIFY, EXCEPT FOR FEW LINES.             *
     *************************************************************************/

    /*
     * This method is called by Android when our activity is first created.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        roll(); 
    }
    @Override
    public void onClick(View view){
        String num1 = billAmount.getText().toString();
        String num2 = tipPercent.getText().toString();
        switch(view.getId()){
            case R.id.button:
            float tip = ((Float.parseFloat(num1) * Float.parseFloat(num2)) / 100);
            tipAmount.setText("Tip: "+String.valueOf(tip));
            break;
        }
        }
    }